version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 3s
      timeout: 2s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 3s
      timeout: 2s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "npx prisma migrate reset --force &&  npm run start:prod"
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - ACCESS_SECRET=access_secret
      - REFRESH_SECRET=refresh_secret
      - REDIS_URL=redis://redis:6379

    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

volumes:
  db_data:
